"""Fit the mock under three likelihoods and compare the width on sigma/m."""
import os, sys, time
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import infocontent as IC

WHICH = sys.argv[1]                       # rho | q | both
NSTEP = int(sys.argv[2]) if len(sys.argv) > 2 else 400
OUT = os.environ.get("OUT", ".")

# ---- the mock, generated by the model itself, with one fixed noise draw ----
r1_t, res_t = IC.r1_for(IC.TRUTH["M200"], IC.TRUTH["c"], IC.TRUTH["sigma_m"])
RHO_T, Q_T = IC.observables(res_t, r1_t)
rng = np.random.default_rng(7)
D_RHO = RHO_T * np.exp(IC.SIG_RHO * rng.standard_normal(RHO_T.size))
D_Q = Q_T + IC.SIG_Q * rng.standard_normal(Q_T.size)
QOK = np.isfinite(D_Q)
LM0 = np.log10(IC.TRUTH["M200"])


def log_prob(p):
    logM200, c, logsm = p
    if not (LM0-0.4 < logM200 < LM0+0.4): return -np.inf
    if not (3.0 < c < 20.0): return -np.inf
    if not (-2.3 < logsm < 0.3): return -np.inf
    r1, res = IC.r1_for(10.0**logM200, c, 10.0**logsm)
    if r1 is None: return -np.inf
    try:
        rho, q = IC.observables(res, r1)
    except Exception:
        return -np.inf
    if not np.all(np.isfinite(rho)): return -np.inf
    ll = 0.0
    if WHICH in ("rho", "both"):
        ll += -0.5*np.sum((np.log(rho/D_RHO)/IC.SIG_RHO)**2)
    if WHICH in ("q", "both"):
        m = QOK & np.isfinite(q)
        if m.sum() < QOK.sum()-1: return -np.inf
        ll += -0.5*np.sum(((q[m]-D_Q[m])/IC.SIG_Q)**2)
    return ll if np.isfinite(ll) else -np.inf


if __name__ == "__main__":
    import emcee
    import multiprocessing as mp
    # SPAWN, not fork. JAX is multithreaded and multiprocessing forks by
    # default on Linux; the combination deadlocks. It is a race rather than a
    # certainty -- earlier runs in this project survived it -- which is
    # exactly what makes it worth pinning down rather than retrying.
    CTX = mp.get_context("spawn")
    print(f"[{WHICH}] truth: M200={IC.TRUTH['M200']:.2e} c={IC.TRUTH['c']} "
          f"sigma/m={IC.TRUTH['sigma_m']}  (r1={r1_t:.2f} kpc)", flush=True)
    t0=time.time(); lp = log_prob(np.array([LM0, 10.0, np.log10(0.5)]))
    print(f"  one call {time.time()-t0:.2f} s, logL at truth = {lp:.2f}", flush=True)

    nw = 24
    rng2 = np.random.default_rng(1)
    seeds = []
    while len(seeds) < nw:
        cand = np.array([LM0+0.08*rng2.standard_normal(),
                         rng2.uniform(6, 15), rng2.uniform(-1.6, 0.1)])
        if np.isfinite(log_prob(cand)): seeds.append(cand)
    t0=time.time()
    with CTX.Pool(8) as pool:
        s = emcee.EnsembleSampler(nw, 3, log_prob, pool=pool)
        s.run_mcmc(np.array(seeds), NSTEP, progress=False)
    print(f"  {NSTEP} steps in {time.time()-t0:.0f} s, acceptance "
          f"{np.mean(s.acceptance_fraction):.2f}", flush=True)
    np.save(f"{OUT}/info_{WHICH}.npy", s.get_chain())
    fl = s.get_chain(discard=NSTEP//2, flat=True)
    q = lambda v: np.percentile(v, [16, 50, 84])
    sm = 10**fl[:, 2]
    lo, mid, hi = q(sm)
    print(f"  M200   : {q(10**fl[:,0])/1e12} x1e12   (truth 1.0)")
    print(f"  c      : {q(fl[:,1])}   (truth 10)")
    print(f"  sigma/m: {mid:.4f} +{hi-mid:.4f} -{mid-lo:.4f}   (truth "
          f"{IC.TRUTH['sigma_m']})   frac width {(hi-lo)/mid:.3f}")
